### Get Operators
GET http://localhost:3000/operator

### Get Operator by ID
GET http://localhost:3000/operator/6127d7e71e5f89d0faa9982d

### Get Operator by ID
GET http://localhost:3000/operator/type

### Get Operator by ID, filter by type
GET http://localhost:3000/operator/type/6127d7e71e5f89d0faa9982d

### Get Operator Names using operator and game type
GET http://localhost:3000/operator/DraftKings/Classic

### Get Operator Names using operator and game type with concat +
GET http://localhost:3000/operator/fanduel/single+game


### Get Players using operator and game type with concat +
GET http://localhost:3000/players?page=1000&limit=10


### Get Players using operator DraftKing
GET http://localhost:3000/players?operator=DraftKing

### Get Players using operator FanDuel
GET http://localhost:3000/players?operator=FanDuel

### Get Players using operatorPlayerName and operator DraftKing
GET http://localhost:3000/players?sortBy=operatorPlayerName&sortDir=asc&operator=DraftKing


### Get Players using operatorPlayerName and operator FanDuel
GET http://localhost:3000/players?sortBy=operatorPlayerName&sortDir=asc&operator=FanDuel

### Get Players using operatorPlayerName and descending order
GET http://localhost:3000/players?sortBy=operatorPlayerName&sortDir=desc&operator=FanDuel

