version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - dev

  mongo-seed:
    build: ./mongo-seed
    networks:
      - dev
    depends_on:
      - mongodb

networks:
  dev:
    name: dev
    driver: bridge