# Operators

### Get Operators
GET http://localhost:3000/operator

### Get Operator by ID
GET http://localhost:3000/operator/6127d7e71e5f89d0faa9982d

# Game Types

### Get game types
GET http://localhost:3000/operator/type

### Get game types, optional filter by operator
GET http://localhost:3000/operator/type/yahoo

# Slate Names

### Get Slate Names using operator and game type
GET http://localhost:3000/operator/DraftKings/Classic

### Get Slate Names using operator and game type with concat +
GET http://localhost:3000/operator/fanduel/single+game

# Players

### Get Players using operator and game type with concat +
GET http://localhost:3000/players?page=1000&limit=10

### Get Players using operator DraftKing
GET http://localhost:3000/players?operator=DraftKing

### Get Players using operator FanDuel
GET http://localhost:3000/players?operator=FanDuel

### Get Players using operatorPlayerName and operator DraftKing
GET http://localhost:3000/players?sortBy=operatorPlayerName&sortDir=asc&operator=DraftKing


### Get Players using operatorPlayerName and operator FanDuel
GET http://localhost:3000/players?sortBy=operatorPlayerName&sortDir=asc&operator=FanDuel

### Get Players using operatorPlayerName and descending order
GET http://localhost:3000/players?sortBy=operatorPlayerName&sortDir=desc&operator=FanDuel

#Errors

### Get 404 if the route doesn't exist
GET http://localhost:3000
